// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s (
        ap_ready,
        data_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28
);


output   ap_ready;
input  [370:0] data_V_read;
output  [24:0] ap_return_0;
output  [24:0] ap_return_1;
output  [24:0] ap_return_2;
output  [24:0] ap_return_3;
output  [24:0] ap_return_4;
output  [24:0] ap_return_5;
output  [24:0] ap_return_6;
output  [24:0] ap_return_7;
output  [24:0] ap_return_8;
output  [24:0] ap_return_9;
output  [24:0] ap_return_10;
output  [24:0] ap_return_11;
output  [24:0] ap_return_12;
output  [24:0] ap_return_13;
output  [24:0] ap_return_14;
output  [24:0] ap_return_15;
output  [24:0] ap_return_16;
output  [24:0] ap_return_17;
output  [24:0] ap_return_18;
output  [24:0] ap_return_19;
output  [24:0] ap_return_20;
output  [24:0] ap_return_21;
output  [24:0] ap_return_22;
output  [24:0] ap_return_23;
output  [24:0] ap_return_24;
output  [24:0] ap_return_25;
output  [24:0] ap_return_26;
output  [24:0] ap_return_27;
output  [24:0] ap_return_28;

wire   [12:0] mul_ln703_10_fu_258_p1;
wire   [12:0] mul_ln703_2_fu_259_p1;
wire   [12:0] mul_ln703_22_fu_260_p1;
wire   [6:0] mul_ln703_28_fu_261_p1;
wire   [12:0] mul_ln703_12_fu_262_p1;
wire   [12:0] mul_ln703_17_fu_263_p1;
wire   [12:0] mul_ln703_3_fu_264_p1;
wire   [12:0] mul_ln703_fu_265_p1;
wire   [12:0] mul_ln703_26_fu_266_p1;
wire   [12:0] mul_ln703_27_fu_267_p1;
wire   [12:0] mul_ln703_24_fu_268_p1;
wire   [12:0] mul_ln703_7_fu_269_p1;
wire   [12:0] mul_ln703_18_fu_270_p1;
wire   [12:0] mul_ln703_9_fu_271_p1;
wire   [12:0] mul_ln703_8_fu_272_p1;
wire   [12:0] mul_ln703_21_fu_273_p1;
wire   [12:0] mul_ln703_20_fu_274_p1;
wire   [12:0] mul_ln703_25_fu_275_p1;
wire   [12:0] mul_ln703_1_fu_276_p1;
wire   [12:0] mul_ln703_23_fu_277_p1;
wire   [12:0] mul_ln703_11_fu_278_p1;
wire   [12:0] mul_ln703_13_fu_279_p1;
wire   [12:0] mul_ln703_4_fu_280_p1;
wire   [12:0] mul_ln703_16_fu_281_p1;
wire   [12:0] mul_ln703_15_fu_282_p1;
wire   [12:0] mul_ln703_6_fu_283_p1;
wire   [12:0] mul_ln703_14_fu_284_p1;
wire   [12:0] mul_ln703_19_fu_285_p1;
wire   [12:0] mul_ln703_5_fu_286_p1;
wire   [12:0] trunc_ln56_fu_3855_p1;
wire   [24:0] mul_ln703_fu_265_p2;
wire   [12:0] tmp_1_fu_3870_p4;
wire   [23:0] mul_ln703_1_fu_276_p2;
wire   [23:0] add_ln703_1_fu_3885_p2;
wire   [12:0] tmp_2_fu_3895_p4;
wire   [23:0] mul_ln703_2_fu_259_p2;
wire   [23:0] add_ln703_2_fu_3910_p2;
wire   [12:0] tmp_3_fu_3920_p4;
wire   [24:0] mul_ln703_3_fu_264_p2;
wire   [12:0] tmp_4_fu_3941_p4;
wire   [24:0] mul_ln703_4_fu_280_p2;
wire   [12:0] tmp_5_fu_3962_p4;
wire   [24:0] mul_ln703_5_fu_286_p2;
wire   [12:0] tmp_6_fu_3983_p4;
wire   [24:0] mul_ln703_6_fu_283_p2;
wire   [12:0] tmp_7_fu_4004_p4;
wire   [24:0] mul_ln703_7_fu_269_p2;
wire   [12:0] tmp_8_fu_4025_p4;
wire   [24:0] mul_ln703_8_fu_272_p2;
wire   [12:0] tmp_9_fu_4046_p4;
wire   [24:0] mul_ln703_9_fu_271_p2;
wire   [12:0] tmp_s_fu_4067_p4;
wire   [24:0] mul_ln703_10_fu_258_p2;
wire   [12:0] tmp_10_fu_4088_p4;
wire   [24:0] mul_ln703_11_fu_278_p2;
wire   [12:0] tmp_11_fu_4109_p4;
wire   [24:0] mul_ln703_12_fu_262_p2;
wire   [12:0] tmp_12_fu_4130_p4;
wire   [24:0] mul_ln703_13_fu_279_p2;
wire   [12:0] tmp_13_fu_4151_p4;
wire   [24:0] mul_ln703_14_fu_284_p2;
wire   [12:0] tmp_14_fu_4172_p4;
wire   [24:0] mul_ln703_15_fu_282_p2;
wire   [12:0] tmp_15_fu_4193_p4;
wire   [24:0] mul_ln703_16_fu_281_p2;
wire   [12:0] tmp_16_fu_4214_p4;
wire   [24:0] mul_ln703_17_fu_263_p2;
wire   [12:0] tmp_17_fu_4235_p4;
wire   [24:0] mul_ln703_18_fu_270_p2;
wire   [12:0] tmp_18_fu_4256_p4;
wire   [24:0] mul_ln703_19_fu_285_p2;
wire   [12:0] tmp_19_fu_4277_p4;
wire   [24:0] mul_ln703_20_fu_274_p2;
wire   [12:0] tmp_20_fu_4298_p4;
wire   [24:0] mul_ln703_21_fu_273_p2;
wire   [12:0] tmp_21_fu_4319_p4;
wire   [24:0] mul_ln703_22_fu_260_p2;
wire   [12:0] tmp_22_fu_4340_p4;
wire   [24:0] mul_ln703_23_fu_277_p2;
wire   [12:0] tmp_23_fu_4361_p4;
wire   [24:0] mul_ln703_24_fu_268_p2;
wire   [12:0] tmp_24_fu_4382_p4;
wire   [24:0] mul_ln703_25_fu_275_p2;
wire   [12:0] tmp_25_fu_4403_p4;
wire   [24:0] mul_ln703_26_fu_266_p2;
wire   [12:0] tmp_26_fu_4424_p4;
wire   [24:0] mul_ln703_27_fu_267_p2;
wire   [6:0] tmp_fu_4445_p4;
wire   [19:0] mul_ln703_28_fu_261_p2;
wire   [19:0] add_ln703_28_fu_4460_p2;
wire   [24:0] add_ln703_fu_3864_p2;
wire  signed [24:0] sext_ln703_fu_3891_p1;
wire  signed [24:0] sext_ln703_1_fu_3916_p1;
wire   [24:0] add_ln703_3_fu_3935_p2;
wire   [24:0] add_ln703_4_fu_3956_p2;
wire   [24:0] add_ln703_5_fu_3977_p2;
wire   [24:0] add_ln703_6_fu_3998_p2;
wire   [24:0] add_ln703_7_fu_4019_p2;
wire   [24:0] add_ln703_8_fu_4040_p2;
wire   [24:0] add_ln703_9_fu_4061_p2;
wire   [24:0] add_ln703_10_fu_4082_p2;
wire   [24:0] add_ln703_11_fu_4103_p2;
wire   [24:0] add_ln703_12_fu_4124_p2;
wire   [24:0] add_ln703_13_fu_4145_p2;
wire   [24:0] add_ln703_14_fu_4166_p2;
wire   [24:0] add_ln703_15_fu_4187_p2;
wire   [24:0] add_ln703_16_fu_4208_p2;
wire   [24:0] add_ln703_17_fu_4229_p2;
wire   [24:0] add_ln703_18_fu_4250_p2;
wire   [24:0] add_ln703_19_fu_4271_p2;
wire   [24:0] add_ln703_20_fu_4292_p2;
wire   [24:0] add_ln703_21_fu_4313_p2;
wire   [24:0] add_ln703_22_fu_4334_p2;
wire   [24:0] add_ln703_23_fu_4355_p2;
wire   [24:0] add_ln703_24_fu_4376_p2;
wire   [24:0] add_ln703_25_fu_4397_p2;
wire   [24:0] add_ln703_26_fu_4418_p2;
wire   [24:0] add_ln703_27_fu_4439_p2;
wire  signed [24:0] sext_ln703_2_fu_4466_p1;
wire   [24:0] mul_ln703_10_fu_258_p10;
wire   [24:0] mul_ln703_11_fu_278_p10;
wire   [24:0] mul_ln703_12_fu_262_p10;
wire   [24:0] mul_ln703_13_fu_279_p10;
wire   [24:0] mul_ln703_14_fu_284_p10;
wire   [24:0] mul_ln703_15_fu_282_p10;
wire   [24:0] mul_ln703_16_fu_281_p10;
wire   [24:0] mul_ln703_17_fu_263_p10;
wire   [24:0] mul_ln703_18_fu_270_p10;
wire   [24:0] mul_ln703_19_fu_285_p10;
wire   [23:0] mul_ln703_1_fu_276_p10;
wire   [24:0] mul_ln703_20_fu_274_p10;
wire   [24:0] mul_ln703_21_fu_273_p10;
wire   [24:0] mul_ln703_22_fu_260_p10;
wire   [24:0] mul_ln703_23_fu_277_p10;
wire   [24:0] mul_ln703_24_fu_268_p10;
wire   [24:0] mul_ln703_25_fu_275_p10;
wire   [24:0] mul_ln703_26_fu_266_p10;
wire   [24:0] mul_ln703_27_fu_267_p10;
wire   [19:0] mul_ln703_28_fu_261_p10;
wire   [23:0] mul_ln703_2_fu_259_p10;
wire   [24:0] mul_ln703_3_fu_264_p10;
wire   [24:0] mul_ln703_4_fu_280_p10;
wire   [24:0] mul_ln703_5_fu_286_p10;
wire   [24:0] mul_ln703_6_fu_283_p10;
wire   [24:0] mul_ln703_7_fu_269_p10;
wire   [24:0] mul_ln703_8_fu_272_p10;
wire   [24:0] mul_ln703_9_fu_271_p10;
wire   [24:0] mul_ln703_fu_265_p10;

assign add_ln703_10_fu_4082_p2 = ($signed(25'd33516480) + $signed(mul_ln703_10_fu_258_p2));

assign add_ln703_11_fu_4103_p2 = ($signed(25'd33491001) + $signed(mul_ln703_11_fu_278_p2));

assign add_ln703_12_fu_4124_p2 = ($signed(25'd33529432) + $signed(mul_ln703_12_fu_262_p2));

assign add_ln703_13_fu_4145_p2 = ($signed(25'd33507652) + $signed(mul_ln703_13_fu_279_p2));

assign add_ln703_14_fu_4166_p2 = ($signed(25'd33533026) + $signed(mul_ln703_14_fu_284_p2));

assign add_ln703_15_fu_4187_p2 = ($signed(25'd33548141) + $signed(mul_ln703_15_fu_282_p2));

assign add_ln703_16_fu_4208_p2 = ($signed(25'd33538755) + $signed(mul_ln703_16_fu_281_p2));

assign add_ln703_17_fu_4229_p2 = ($signed(25'd33528062) + $signed(mul_ln703_17_fu_263_p2));

assign add_ln703_18_fu_4250_p2 = ($signed(25'd33545973) + $signed(mul_ln703_18_fu_270_p2));

assign add_ln703_19_fu_4271_p2 = ($signed(25'd33542580) + $signed(mul_ln703_19_fu_285_p2));

assign add_ln703_1_fu_3885_p2 = ($signed(24'd16620888) + $signed(mul_ln703_1_fu_276_p2));

assign add_ln703_20_fu_4292_p2 = ($signed(25'd33537908) + $signed(mul_ln703_20_fu_274_p2));

assign add_ln703_21_fu_4313_p2 = ($signed(25'd33548064) + $signed(mul_ln703_21_fu_273_p2));

assign add_ln703_22_fu_4334_p2 = ($signed(25'd33548880) + $signed(mul_ln703_22_fu_260_p2));

assign add_ln703_23_fu_4355_p2 = ($signed(25'd33520600) + $signed(mul_ln703_23_fu_277_p2));

assign add_ln703_24_fu_4376_p2 = ($signed(25'd33315286) + $signed(mul_ln703_24_fu_268_p2));

assign add_ln703_25_fu_4397_p2 = ($signed(25'd33457410) + $signed(mul_ln703_25_fu_275_p2));

assign add_ln703_26_fu_4418_p2 = ($signed(25'd33473578) + $signed(mul_ln703_26_fu_266_p2));

assign add_ln703_27_fu_4439_p2 = ($signed(25'd33301594) + $signed(mul_ln703_27_fu_267_p2));

assign add_ln703_28_fu_4460_p2 = ($signed(20'd775349) + $signed(mul_ln703_28_fu_261_p2));

assign add_ln703_2_fu_3910_p2 = ($signed(24'd16590157) + $signed(mul_ln703_2_fu_259_p2));

assign add_ln703_3_fu_3935_p2 = ($signed(25'd33479165) + $signed(mul_ln703_3_fu_264_p2));

assign add_ln703_4_fu_3956_p2 = ($signed(25'd33338996) + $signed(mul_ln703_4_fu_280_p2));

assign add_ln703_5_fu_3977_p2 = ($signed(25'd33353299) + $signed(mul_ln703_5_fu_286_p2));

assign add_ln703_6_fu_3998_p2 = ($signed(25'd33514625) + $signed(mul_ln703_6_fu_283_p2));

assign add_ln703_7_fu_4019_p2 = ($signed(25'd33506722) + $signed(mul_ln703_7_fu_269_p2));

assign add_ln703_8_fu_4040_p2 = ($signed(25'd33504145) + $signed(mul_ln703_8_fu_272_p2));

assign add_ln703_9_fu_4061_p2 = ($signed(25'd33534728) + $signed(mul_ln703_9_fu_271_p2));

assign add_ln703_fu_3864_p2 = ($signed(25'd33393578) + $signed(mul_ln703_fu_265_p2));

assign ap_ready = 1'b1;

assign ap_return_0 = add_ln703_fu_3864_p2;

assign ap_return_1 = sext_ln703_fu_3891_p1;

assign ap_return_10 = add_ln703_10_fu_4082_p2;

assign ap_return_11 = add_ln703_11_fu_4103_p2;

assign ap_return_12 = add_ln703_12_fu_4124_p2;

assign ap_return_13 = add_ln703_13_fu_4145_p2;

assign ap_return_14 = add_ln703_14_fu_4166_p2;

assign ap_return_15 = add_ln703_15_fu_4187_p2;

assign ap_return_16 = add_ln703_16_fu_4208_p2;

assign ap_return_17 = add_ln703_17_fu_4229_p2;

assign ap_return_18 = add_ln703_18_fu_4250_p2;

assign ap_return_19 = add_ln703_19_fu_4271_p2;

assign ap_return_2 = sext_ln703_1_fu_3916_p1;

assign ap_return_20 = add_ln703_20_fu_4292_p2;

assign ap_return_21 = add_ln703_21_fu_4313_p2;

assign ap_return_22 = add_ln703_22_fu_4334_p2;

assign ap_return_23 = add_ln703_23_fu_4355_p2;

assign ap_return_24 = add_ln703_24_fu_4376_p2;

assign ap_return_25 = add_ln703_25_fu_4397_p2;

assign ap_return_26 = add_ln703_26_fu_4418_p2;

assign ap_return_27 = add_ln703_27_fu_4439_p2;

assign ap_return_28 = sext_ln703_2_fu_4466_p1;

assign ap_return_3 = add_ln703_3_fu_3935_p2;

assign ap_return_4 = add_ln703_4_fu_3956_p2;

assign ap_return_5 = add_ln703_5_fu_3977_p2;

assign ap_return_6 = add_ln703_6_fu_3998_p2;

assign ap_return_7 = add_ln703_7_fu_4019_p2;

assign ap_return_8 = add_ln703_8_fu_4040_p2;

assign ap_return_9 = add_ln703_9_fu_4061_p2;

assign mul_ln703_10_fu_258_p1 = mul_ln703_10_fu_258_p10;

assign mul_ln703_10_fu_258_p10 = tmp_s_fu_4067_p4;

assign mul_ln703_10_fu_258_p2 = (25'd85590 * mul_ln703_10_fu_258_p1);

assign mul_ln703_11_fu_278_p1 = mul_ln703_11_fu_278_p10;

assign mul_ln703_11_fu_278_p10 = tmp_10_fu_4088_p4;

assign mul_ln703_11_fu_278_p2 = (25'd98126 * mul_ln703_11_fu_278_p1);

assign mul_ln703_12_fu_262_p1 = mul_ln703_12_fu_262_p10;

assign mul_ln703_12_fu_262_p10 = tmp_11_fu_4109_p4;

assign mul_ln703_12_fu_262_p2 = (25'd10090 * mul_ln703_12_fu_262_p1);

assign mul_ln703_13_fu_279_p1 = mul_ln703_13_fu_279_p10;

assign mul_ln703_13_fu_279_p10 = tmp_12_fu_4130_p4;

assign mul_ln703_13_fu_279_p2 = (25'd12030 * mul_ln703_13_fu_279_p1);

assign mul_ln703_14_fu_284_p1 = mul_ln703_14_fu_284_p10;

assign mul_ln703_14_fu_284_p10 = tmp_13_fu_4151_p4;

assign mul_ln703_14_fu_284_p2 = (25'd10320 * mul_ln703_14_fu_284_p1);

assign mul_ln703_15_fu_282_p1 = mul_ln703_15_fu_282_p10;

assign mul_ln703_15_fu_282_p10 = tmp_14_fu_4172_p4;

assign mul_ln703_15_fu_282_p2 = (25'd11063 * mul_ln703_15_fu_282_p1);

assign mul_ln703_16_fu_281_p1 = mul_ln703_16_fu_281_p10;

assign mul_ln703_16_fu_281_p10 = tmp_15_fu_4193_p4;

assign mul_ln703_16_fu_281_p2 = (25'd7799 * mul_ln703_16_fu_281_p1);

assign mul_ln703_17_fu_263_p1 = mul_ln703_17_fu_263_p10;

assign mul_ln703_17_fu_263_p10 = tmp_16_fu_4214_p4;

assign mul_ln703_17_fu_263_p2 = (25'd20311 * mul_ln703_17_fu_263_p1);

assign mul_ln703_18_fu_270_p1 = mul_ln703_18_fu_270_p10;

assign mul_ln703_18_fu_270_p10 = tmp_17_fu_4235_p4;

assign mul_ln703_18_fu_270_p2 = (25'd28108 * mul_ln703_18_fu_270_p1);

assign mul_ln703_19_fu_285_p1 = mul_ln703_19_fu_285_p10;

assign mul_ln703_19_fu_285_p10 = tmp_18_fu_4256_p4;

assign mul_ln703_19_fu_285_p2 = (25'd21420 * mul_ln703_19_fu_285_p1);

assign mul_ln703_1_fu_276_p1 = mul_ln703_1_fu_276_p10;

assign mul_ln703_1_fu_276_p10 = tmp_1_fu_3870_p4;

assign mul_ln703_1_fu_276_p2 = (24'd973 * mul_ln703_1_fu_276_p1);

assign mul_ln703_20_fu_274_p1 = mul_ln703_20_fu_274_p10;

assign mul_ln703_20_fu_274_p10 = tmp_19_fu_4277_p4;

assign mul_ln703_20_fu_274_p2 = (25'd38818 * mul_ln703_20_fu_274_p1);

assign mul_ln703_21_fu_273_p1 = mul_ln703_21_fu_273_p10;

assign mul_ln703_21_fu_273_p10 = tmp_20_fu_4298_p4;

assign mul_ln703_21_fu_273_p2 = (25'd23301 * mul_ln703_21_fu_273_p1);

assign mul_ln703_22_fu_260_p1 = mul_ln703_22_fu_260_p10;

assign mul_ln703_22_fu_260_p10 = tmp_21_fu_4319_p4;

assign mul_ln703_22_fu_260_p2 = (25'd30223 * mul_ln703_22_fu_260_p1);

assign mul_ln703_23_fu_277_p1 = mul_ln703_23_fu_277_p10;

assign mul_ln703_23_fu_277_p10 = tmp_22_fu_4340_p4;

assign mul_ln703_23_fu_277_p2 = (25'd40710 * mul_ln703_23_fu_277_p1);

assign mul_ln703_24_fu_268_p1 = mul_ln703_24_fu_268_p10;

assign mul_ln703_24_fu_268_p10 = tmp_23_fu_4361_p4;

assign mul_ln703_24_fu_268_p2 = (25'd30113 * mul_ln703_24_fu_268_p1);

assign mul_ln703_25_fu_275_p1 = mul_ln703_25_fu_275_p10;

assign mul_ln703_25_fu_275_p10 = tmp_24_fu_4382_p4;

assign mul_ln703_25_fu_275_p2 = (25'd12361 * mul_ln703_25_fu_275_p1);

assign mul_ln703_26_fu_266_p1 = mul_ln703_26_fu_266_p10;

assign mul_ln703_26_fu_266_p10 = tmp_25_fu_4403_p4;

assign mul_ln703_26_fu_266_p2 = (25'd12413 * mul_ln703_26_fu_266_p1);

assign mul_ln703_27_fu_267_p1 = mul_ln703_27_fu_267_p10;

assign mul_ln703_27_fu_267_p10 = tmp_26_fu_4424_p4;

assign mul_ln703_27_fu_267_p2 = (25'd28516 * mul_ln703_27_fu_267_p1);

assign mul_ln703_28_fu_261_p1 = mul_ln703_28_fu_261_p10;

assign mul_ln703_28_fu_261_p10 = tmp_fu_4445_p4;

assign mul_ln703_28_fu_261_p2 = (20'd5531 * mul_ln703_28_fu_261_p1);

assign mul_ln703_2_fu_259_p1 = mul_ln703_2_fu_259_p10;

assign mul_ln703_2_fu_259_p10 = tmp_2_fu_3895_p4;

assign mul_ln703_2_fu_259_p2 = (24'd835 * mul_ln703_2_fu_259_p1);

assign mul_ln703_3_fu_264_p1 = mul_ln703_3_fu_264_p10;

assign mul_ln703_3_fu_264_p10 = tmp_3_fu_3920_p4;

assign mul_ln703_3_fu_264_p2 = (25'd1424 * mul_ln703_3_fu_264_p1);

assign mul_ln703_4_fu_280_p1 = mul_ln703_4_fu_280_p10;

assign mul_ln703_4_fu_280_p10 = tmp_4_fu_3941_p4;

assign mul_ln703_4_fu_280_p2 = (25'd1812 * mul_ln703_4_fu_280_p1);

assign mul_ln703_5_fu_286_p1 = mul_ln703_5_fu_286_p10;

assign mul_ln703_5_fu_286_p10 = tmp_5_fu_3962_p4;

assign mul_ln703_5_fu_286_p2 = (25'd3645 * mul_ln703_5_fu_286_p1);

assign mul_ln703_6_fu_283_p1 = mul_ln703_6_fu_283_p10;

assign mul_ln703_6_fu_283_p10 = tmp_6_fu_3983_p4;

assign mul_ln703_6_fu_283_p2 = (25'd77995 * mul_ln703_6_fu_283_p1);

assign mul_ln703_7_fu_269_p1 = mul_ln703_7_fu_269_p10;

assign mul_ln703_7_fu_269_p10 = tmp_7_fu_4004_p4;

assign mul_ln703_7_fu_269_p2 = (25'd63786 * mul_ln703_7_fu_269_p1);

assign mul_ln703_8_fu_272_p1 = mul_ln703_8_fu_272_p10;

assign mul_ln703_8_fu_272_p10 = tmp_8_fu_4025_p4;

assign mul_ln703_8_fu_272_p2 = (25'd69595 * mul_ln703_8_fu_272_p1);

assign mul_ln703_9_fu_271_p1 = mul_ln703_9_fu_271_p10;

assign mul_ln703_9_fu_271_p10 = tmp_9_fu_4046_p4;

assign mul_ln703_9_fu_271_p2 = (25'd61905 * mul_ln703_9_fu_271_p1);

assign mul_ln703_fu_265_p1 = mul_ln703_fu_265_p10;

assign mul_ln703_fu_265_p10 = trunc_ln56_fu_3855_p1;

assign mul_ln703_fu_265_p2 = (25'd1485 * mul_ln703_fu_265_p1);

assign sext_ln703_1_fu_3916_p1 = $signed(add_ln703_2_fu_3910_p2);

assign sext_ln703_2_fu_4466_p1 = $signed(add_ln703_28_fu_4460_p2);

assign sext_ln703_fu_3891_p1 = $signed(add_ln703_1_fu_3885_p2);

assign tmp_10_fu_4088_p4 = {{data_V_read[155:143]}};

assign tmp_11_fu_4109_p4 = {{data_V_read[168:156]}};

assign tmp_12_fu_4130_p4 = {{data_V_read[181:169]}};

assign tmp_13_fu_4151_p4 = {{data_V_read[194:182]}};

assign tmp_14_fu_4172_p4 = {{data_V_read[207:195]}};

assign tmp_15_fu_4193_p4 = {{data_V_read[220:208]}};

assign tmp_16_fu_4214_p4 = {{data_V_read[233:221]}};

assign tmp_17_fu_4235_p4 = {{data_V_read[246:234]}};

assign tmp_18_fu_4256_p4 = {{data_V_read[259:247]}};

assign tmp_19_fu_4277_p4 = {{data_V_read[272:260]}};

assign tmp_1_fu_3870_p4 = {{data_V_read[25:13]}};

assign tmp_20_fu_4298_p4 = {{data_V_read[285:273]}};

assign tmp_21_fu_4319_p4 = {{data_V_read[298:286]}};

assign tmp_22_fu_4340_p4 = {{data_V_read[311:299]}};

assign tmp_23_fu_4361_p4 = {{data_V_read[324:312]}};

assign tmp_24_fu_4382_p4 = {{data_V_read[337:325]}};

assign tmp_25_fu_4403_p4 = {{data_V_read[350:338]}};

assign tmp_26_fu_4424_p4 = {{data_V_read[363:351]}};

assign tmp_2_fu_3895_p4 = {{data_V_read[38:26]}};

assign tmp_3_fu_3920_p4 = {{data_V_read[51:39]}};

assign tmp_4_fu_3941_p4 = {{data_V_read[64:52]}};

assign tmp_5_fu_3962_p4 = {{data_V_read[77:65]}};

assign tmp_6_fu_3983_p4 = {{data_V_read[90:78]}};

assign tmp_7_fu_4004_p4 = {{data_V_read[103:91]}};

assign tmp_8_fu_4025_p4 = {{data_V_read[116:104]}};

assign tmp_9_fu_4046_p4 = {{data_V_read[129:117]}};

assign tmp_fu_4445_p4 = {{data_V_read[370:364]}};

assign tmp_s_fu_4067_p4 = {{data_V_read[142:130]}};

assign trunc_ln56_fu_3855_p1 = data_V_read[12:0];

endmodule //normalize_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s
