set_property PACKAGE_PIN AR10 [get_ports {refclk_p[0]}]
set_property PACKAGE_PIN AF8 [get_ports {refclk_p[1]}]
set_property PACKAGE_PIN N10 [get_ports {refclk_p[2]}]
set_property PACKAGE_PIN E10 [get_ports {refclk_p[3]}]
set_property PACKAGE_PIN AR35 [get_ports {refclk_p[4]}]
set_property PACKAGE_PIN AF37 [get_ports {refclk_p[5]}]
set_property PACKAGE_PIN N35 [get_ports {refclk_p[6]}]
set_property PACKAGE_PIN E35 [get_ports {refclk_p[7]}]
set_property PACKAGE_PIN BB8 [get_ports {refclk_p[8]}]
set_property PACKAGE_PIN AH8 [get_ports {refclk_p[9]}]
set_property PACKAGE_PIN R10 [get_ports {refclk_p[10]}]
set_property PACKAGE_PIN G10 [get_ports {refclk_p[11]}]
set_property PACKAGE_PIN AT37 [get_ports {refclk_p[12]}]
set_property PACKAGE_PIN AH37 [get_ports {refclk_p[13]}]
set_property PACKAGE_PIN R35 [get_ports {refclk_p[14]}]
set_property PACKAGE_PIN G35 [get_ports {refclk_p[15]}]
create_clock -period 8.000 -name refclk_p0 [get_ports {refclk_p[0]}]
create_clock -period 8.000 -name refclk_p1 [get_ports {refclk_p[1]}]
create_clock -period 8.000 -name refclk_p2 [get_ports {refclk_p[2]}]
create_clock -period 8.000 -name refclk_p3 [get_ports {refclk_p[3]}]
create_clock -period 8.000 -name refclk_p4 [get_ports {refclk_p[4]}]
create_clock -period 8.000 -name refclk_p5 [get_ports {refclk_p[5]}]
create_clock -period 8.000 -name refclk_p6 [get_ports {refclk_p[6]}]
create_clock -period 8.000 -name refclk_p7 [get_ports {refclk_p[7]}]
create_clock -period 1.563 -name refclk_p8 [get_ports {refclk_p[8]}]
create_clock -period 1.563 -name refclk_p9 [get_ports {refclk_p[9]}]
create_clock -period 1.563 -name refclk_p10 [get_ports {refclk_p[10]}]
create_clock -period 1.563 -name refclk_p11 [get_ports {refclk_p[11]}]
create_clock -period 1.563 -name refclk_p12 [get_ports {refclk_p[12]}]
create_clock -period 1.563 -name refclk_p13 [get_ports {refclk_p[13]}]
create_clock -period 1.563 -name refclk_p14 [get_ports {refclk_p[14]}]
create_clock -period 1.563 -name refclk_p15 [get_ports {refclk_p[15]}]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p0]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p1]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p2]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p3]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p4]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p5]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p6]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p7]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p8]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p9]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p10]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p11]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p12]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p13]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p14]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks refclk_p15]
set_property LOC GTHE2_CHANNEL_X0Y6 [get_cells {*/quad_loop[0].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y7 [get_cells {*/quad_loop[0].GTHE2_QUAD_inst/mgt_loop[3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y8 [get_cells {*/quad_loop[1].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y9 [get_cells {*/quad_loop[1].GTHE2_QUAD_inst/mgt_loop[1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y10 [get_cells {*/quad_loop[1].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y11 [get_cells {*/quad_loop[1].GTHE2_QUAD_inst/mgt_loop[3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y12 [get_cells {*/quad_loop[2].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y13 [get_cells {*/quad_loop[2].GTHE2_QUAD_inst/mgt_loop[1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y14 [get_cells {*/quad_loop[2].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y15 [get_cells {*/quad_loop[2].GTHE2_QUAD_inst/mgt_loop[3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y16 [get_cells {*/quad_loop[3].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y17 [get_cells {*/quad_loop[3].GTHE2_QUAD_inst/mgt_loop[1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y18 [get_cells {*/quad_loop[3].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y19 [get_cells {*/quad_loop[3].GTHE2_QUAD_inst/mgt_loop[3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y20 [get_cells {*/quad_loop[4].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y21 [get_cells {*/quad_loop[4].GTHE2_QUAD_inst/mgt_loop[1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y22 [get_cells {*/quad_loop[4].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y23 [get_cells {*/quad_loop[4].GTHE2_QUAD_inst/mgt_loop[3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y24 [get_cells {*/quad_loop[5].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y25 [get_cells {*/quad_loop[5].GTHE2_QUAD_inst/mgt_loop[1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y26 [get_cells {*/quad_loop[5].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y28 [get_cells {*/quad_loop[6].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y29 [get_cells {*/quad_loop[6].GTHE2_QUAD_inst/mgt_loop[1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y30 [get_cells {*/quad_loop[6].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y31 [get_cells {*/quad_loop[6].GTHE2_QUAD_inst/mgt_loop[3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y32 [get_cells {*/quad_loop[7].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y34 [get_cells {*/quad_loop[7].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y37 [get_cells {*/quad_loop[8].GTHE2_QUAD_inst/mgt_loop[1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y38 [get_cells {*/quad_loop[8].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X0Y39 [get_cells {*/quad_loop[8].GTHE2_QUAD_inst/mgt_loop[3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y4 [get_cells {*/quad_loop[9].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y6 [get_cells {*/quad_loop[9].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y7 [get_cells {*/quad_loop[9].GTHE2_QUAD_inst/mgt_loop[3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y8 [get_cells {*/quad_loop[10].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y9 [get_cells {*/quad_loop[10].GTHE2_QUAD_inst/mgt_loop[1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y10 [get_cells {*/quad_loop[10].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y11 [get_cells {*/quad_loop[10].GTHE2_QUAD_inst/mgt_loop[3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y12 [get_cells {*/quad_loop[11].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y13 [get_cells {*/quad_loop[11].GTHE2_QUAD_inst/mgt_loop[1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y14 [get_cells {*/quad_loop[11].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y15 [get_cells {*/quad_loop[11].GTHE2_QUAD_inst/mgt_loop[3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y16 [get_cells {*/quad_loop[12].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y17 [get_cells {*/quad_loop[12].GTHE2_QUAD_inst/mgt_loop[1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y18 [get_cells {*/quad_loop[12].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y19 [get_cells {*/quad_loop[12].GTHE2_QUAD_inst/mgt_loop[3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y20 [get_cells {*/quad_loop[13].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y21 [get_cells {*/quad_loop[13].GTHE2_QUAD_inst/mgt_loop[1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y22 [get_cells {*/quad_loop[13].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y23 [get_cells {*/quad_loop[13].GTHE2_QUAD_inst/mgt_loop[3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y24 [get_cells {*/quad_loop[14].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y25 [get_cells {*/quad_loop[14].GTHE2_QUAD_inst/mgt_loop[1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y26 [get_cells {*/quad_loop[14].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y27 [get_cells {*/quad_loop[14].GTHE2_QUAD_inst/mgt_loop[3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y28 [get_cells {*/quad_loop[15].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y29 [get_cells {*/quad_loop[15].GTHE2_QUAD_inst/mgt_loop[1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y30 [get_cells {*/quad_loop[15].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y31 [get_cells {*/quad_loop[15].GTHE2_QUAD_inst/mgt_loop[3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y32 [get_cells {*/quad_loop[16].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y33 [get_cells {*/quad_loop[16].GTHE2_QUAD_inst/mgt_loop[1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y36 [get_cells {*/quad_loop[17].GTHE2_QUAD_inst/mgt_loop[0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y37 [get_cells {*/quad_loop[17].GTHE2_QUAD_inst/mgt_loop[1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y38 [get_cells {*/quad_loop[17].GTHE2_QUAD_inst/mgt_loop[2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
set_property LOC GTHE2_CHANNEL_X1Y39 [get_cells {*/quad_loop[17].GTHE2_QUAD_inst/mgt_loop[3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst}]
create_clock -period 6.252 -name rxclk0_6 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_7 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_8 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_9 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_10 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_11 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_12 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_13 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_14 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_15 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_16 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_17 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_18 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_19 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_20 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_21 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_22 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_23 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_24 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_25 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_26 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_28 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 4.000 -name rxclk0_29 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]
create_clock -period 4.000 -name rxclk0_30 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_31 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
create_clock -period 4.000 -name txclk0_31 [get_pins -filter REF_PIN_NAME=~*TXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
create_clock -period 4.000 -name rxclk0_32 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk0_34 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 3.125 -name rxclk0_37 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]
create_clock -period 3.125 -name rxclk0_38 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 3.125 -name rxclk0_39 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_4 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 4.000 -name txclk1_4 [get_pins -filter REF_PIN_NAME=~*TXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_6 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_7 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_8 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_9 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_10 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_11 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_12 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_13 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_14 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_15 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_16 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_17 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_18 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_19 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_20 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_21 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_22 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_23 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_24 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_25 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_26 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_27 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
create_clock -period 4.000 -name rxclk1_28 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 4.000 -name rxclk1_29 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]
create_clock -period 4.000 -name rxclk1_30 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 4.000 -name rxclk1_31 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_32 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[16]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 6.252 -name rxclk1_33 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[16]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]
create_clock -period 3.125 -name rxclk1_36 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]
create_clock -period 3.125 -name rxclk1_37 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]
create_clock -period 3.125 -name rxclk1_38 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]
create_clock -period 3.125 -name rxclk1_39 [get_pins -filter REF_PIN_NAME=~*RXOUTCLK -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_6]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_7]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_8]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_9]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_10]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_11]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_12]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_13]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_14]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_15]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_16]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_17]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_18]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_19]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_20]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_21]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_22]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_23]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_24]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_25]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_26]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_28]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_29]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_30]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_31]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks txclk0_31]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_32]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_34]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_37]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_38]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk0_39]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_4]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks txclk1_4]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_6]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_7]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_8]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_9]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_10]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_11]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_12]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_13]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_14]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_15]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_16]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_17]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_18]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_19]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_20]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_21]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_22]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_23]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_24]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_25]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_26]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_27]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_28]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_29]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_30]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_31]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_32]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_33]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_36]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_37]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_38]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks rxclk1_39]

