create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list emtf_sio/CPPF_7_mmcm_clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[0]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[1]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[2]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[3]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[4]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[5]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[6]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[7]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[8]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[9]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[10]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[11]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[12]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[13]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[14]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[15]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[16]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[17]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[18]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[19]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[20]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[21]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[22]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[23]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[24]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[25]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[26]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[27]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[28]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[29]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[30]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txcharisk[0]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txcharisk[1]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txcharisk[2]} {gmt_reclock_loop[0].gmt_tx_rc/mgttx\\.txcharisk[3]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list emtf_sio/CPPF_3_mmcm_clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 32 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[0]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[1]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[2]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[3]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[4]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[5]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[6]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[7]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[8]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[9]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[10]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[11]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[12]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[13]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[14]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[15]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[16]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[17]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[18]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[19]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[20]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[21]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[22]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[23]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[24]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[25]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[26]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[27]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[28]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[29]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[30]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txdata[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 4 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txcharisk[0]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txcharisk[1]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txcharisk[2]} {gmt_reclock_loop[1].gmt_tx_rc/mgttx\\.txcharisk[3]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_i/bscan_dbghub/inst/xsdbm]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_i/bscan_dbghub/inst/xsdbm]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_i/bscan_dbghub/inst/xsdbm]
connect_debug_port dbg_i/bscan_dbghub/inst/xsdbm/clk [get_nets dbg_i/bscan_dbghub/inst/clk]
