
create_generated_clock -name dbg_i/jtag_proc_i/tck_i_w -source [get_ports pcie_clk] -divide_by 8 [get_pins dbg_i/jtag_proc_i/tck_i_reg/Q]
create_generated_clock -name {ptlut/cc/clk_div_b_reg[11]} -source [get_pins usrclk_mmcm_/inst/mmcm_adv_inst/CLKOUT3] -divide_by 2048 [get_pins {ptlut/cc/clk_div_b_reg[11]/Q}]
create_generated_clock -name {pt_dk_n_[0]} -source [get_pins {ptlut/oddr_loop[0].oddr_dk_n/C}] -divide_by 1 -invert [get_ports {pt_dk_n_[0]}]
create_generated_clock -name {pt_dk_n_[1]} -source [get_pins {ptlut/oddr_loop[1].oddr_dk_n/C}] -divide_by 1 -invert [get_ports {pt_dk_n_[1]}]
create_generated_clock -name {pt_dk_n_[2]} -source [get_pins {ptlut/oddr_loop[2].oddr_dk_n/C}] -divide_by 1 -invert [get_ports {pt_dk_n_[2]}]
create_generated_clock -name {pt_dk_n_[3]} -source [get_pins {ptlut/oddr_loop[3].oddr_dk_n/C}] -divide_by 1 -invert [get_ports {pt_dk_n_[3]}]
create_generated_clock -name {pt_dk_n_[4]} -source [get_pins {ptlut/oddr_loop[4].oddr_dk_n/C}] -divide_by 1 -invert [get_ports {pt_dk_n_[4]}]
create_generated_clock -name {pt_dk_n_[5]} -source [get_pins {ptlut/oddr_loop[5].oddr_dk_n/C}] -divide_by 1 -invert [get_ports {pt_dk_n_[5]}]
create_generated_clock -name {pt_dk_n_[6]} -source [get_pins {ptlut/oddr_loop[6].oddr_dk_n/C}] -divide_by 1 -invert [get_ports {pt_dk_n_[6]}]
create_generated_clock -name {pt_dk_n_[7]} -source [get_pins {ptlut/oddr_loop[7].oddr_dk_n/C}] -divide_by 1 -invert [get_ports {pt_dk_n_[7]}]
create_generated_clock -name {pt_dk_p_[0]} -source [get_pins {ptlut/oddr_loop[0].oddr_dk_p/C}] -divide_by 1 [get_ports {pt_dk_p_[0]}]
create_generated_clock -name {pt_dk_p_[1]} -source [get_pins {ptlut/oddr_loop[1].oddr_dk_p/C}] -divide_by 1 [get_ports {pt_dk_p_[1]}]
create_generated_clock -name {pt_dk_p_[2]} -source [get_pins {ptlut/oddr_loop[2].oddr_dk_p/C}] -divide_by 1 [get_ports {pt_dk_p_[2]}]
create_generated_clock -name {pt_dk_p_[3]} -source [get_pins {ptlut/oddr_loop[3].oddr_dk_p/C}] -divide_by 1 [get_ports {pt_dk_p_[3]}]
create_generated_clock -name {pt_dk_p_[4]} -source [get_pins {ptlut/oddr_loop[4].oddr_dk_p/C}] -divide_by 1 [get_ports {pt_dk_p_[4]}]
create_generated_clock -name {pt_dk_p_[5]} -source [get_pins {ptlut/oddr_loop[5].oddr_dk_p/C}] -divide_by 1 [get_ports {pt_dk_p_[5]}]
create_generated_clock -name {pt_dk_p_[6]} -source [get_pins {ptlut/oddr_loop[6].oddr_dk_p/C}] -divide_by 1 [get_ports {pt_dk_p_[6]}]
create_generated_clock -name {pt_dk_p_[7]} -source [get_pins {ptlut/oddr_loop[7].oddr_dk_p/C}] -divide_by 1 [get_ports {pt_dk_p_[7]}]
create_generated_clock -name ptclk_n_ -source [get_pins oddr_dk_n/C] -divide_by 1 -invert [get_ports ptclk_n_]
create_generated_clock -name ptclk_p_ -source [get_pins oddr_dk_p/C] -divide_by 1 [get_ports ptclk_p_]
